### ISSUE TITLE
Timeouts from dinghy ping causing crash?

### ISSUE THREAD

**Issue by seeingidog2** [silvermullet/dinghy-ping#28]
I'm seeing 503 errors when using Dingy ping to test endpoints that are unreachable.

Timeout is being caught by these lines but perhaps there's a mismatch in timeouts between kube-proxy and request library used here?
https://github.com/silvermullet/dinghy-ping/blob/master/api.py#L119-L121

Maybe need a test case around this.

**Comment by sepulworld** [comment]
Per our in person discussion sounds like we might want a tunable timeout setting
