### ISSUE TITLE
Missing static image

### ISSUE THREAD

**Issue by sepulworld** [silvermullet/dinghy-ping#83]
<img width="525" alt="Screen Shot 2019-08-07 at 11 35 11 AM" src="https://user-images.githubusercontent.com/538171/62648742-492be080-b908-11e9-9b9a-9ad0e3638960.png">

**Comment by sepulworld** [comment]
I think since part 1 of cleanup this is broken. should be easy fix

**Comment by balrubaye** [comment]
Hey gang! I see it working fine on prod !

**Comment by sepulworld** [comment]
This broke after @tatianajiselle recent changes. We haven’t tagged a new release of master branch yet

**Comment by tatianajiselle** [comment]
opps hehehe

**Comment by sepulworld** [comment]
Fixed in v0.3.3, also tagged your changes @tatianajiselle in v0.3.3
